(in-package #:schema-protocol-json)

(defun %js (&rest plist)
  (let ((ht (make-hash-table :test #'equal)))
    (loop for (k v) on plist by #'cddr
          when v
            do (setf (gethash (if (stringp k) k (string-downcase (symbol-name k))) ht) v))
    ht))

(defun %set (table key value)
  (when value
    (setf (gethash key table) value))
  table)

(defun type-json-schema (spec slot defs)
  (let ((kind (type-kind spec)))
    (ecase kind
      (:any (make-hash-table :test #'equal))
      (:null (%js "type" "null"))
      (:string
       (let ((ht (%js "type" "string")))
         (%set ht "minLength" (and slot (slot-min-length slot)))
         (%set ht "maxLength" (and slot (slot-max-length slot)))
         (when (and slot (slot-format slot))
           (setf (gethash "format" ht)
                 (string-downcase (symbol-name (slot-format slot)))))
         (when (and slot (slot-description slot))
           (setf (gethash "description" ht) (slot-description slot)))
         ht))
      ((:integer :number :real :float)
       (let ((ht (%js "type" (if (eq kind :integer) "integer" "number"))))
         (%set ht "minimum" (and slot (slot-minimum slot)))
         (%set ht "maximum" (and slot (slot-maximum slot)))
         ht))
      (:boolean (%js "type" "boolean"))
      (:keyword (%js "type" "string"))
      (:symbol (%js "type" "string"))
      (:hash-table (%js "type" "object"))
      (:member (%js "enum" (coerce (type-args spec) 'vector)))
      (:enum (%js "enum" (coerce (enum-members spec) 'vector)))
      (:eql (%js "const" (second spec)))
      (:satisfies (%js "type" "object"))
      (:lisp (make-hash-table :test #'equal))
      (:or
       (let ((ht (make-hash-table :test #'equal)))
         (setf (gethash "anyOf" ht)
               (map 'vector (lambda (s) (type-json-schema s slot defs)) (type-args spec)))
         ht))
      ((:vector :list :sequence)
       (let ((ht (%js "type" "array"))
             (elt (sequence-element-type spec slot)))
         (%set ht "minItems" (and slot (slot-min-length slot)))
         (%set ht "maxItems" (and slot (slot-max-length slot)))
         (when elt
           (setf (gethash "items" ht) (type-json-schema elt slot defs)))
         ht))
      (:nested
       (let* ((name spec)
              (ref (format nil "#/$defs/~A" (string-downcase (symbol-name name)))))
         (ensure-def name defs)
         (%js "$ref" ref))))))

(defun emit-tagged (class defs)
  (let* ((tag (schema-tag class))
         (slot (schema-slot class tag))
         (prop (slot-wire-key slot class))
         (mapping (make-hash-table :test #'equal))
         (one-of '()))
    (dolist (v (reverse (schema-variants class)))
      (let* ((vname (class-name v))
             (key (string-downcase (symbol-name vname)))
             (ref (format nil "#/$defs/~A" key)))
        (ensure-def vname defs)
        (push (%js "$ref" ref) one-of)
        (dolist (tv (variant-tag-values v tag))
          (setf (gethash (stringify-key tv) mapping) ref))))
    (let ((ht (make-hash-table :test #'equal)))
      (setf (gethash "oneOf" ht) (coerce one-of 'vector))
      (let ((disc (make-hash-table :test #'equal)))
        (setf (gethash "propertyName" disc) prop)
        (setf (gethash "mapping" disc) mapping)
        (setf (gethash "discriminator" ht) disc))
      (setf (gethash "title" ht) (string-downcase (symbol-name (class-name class))))
      ht)))

(defun object-json-schema (class defs)
  (finalize-schema class)
  (when (and (schema-tag class) (schema-variants class))
    (return-from object-json-schema (emit-tagged class defs)))
  (let ((props (make-hash-table :test #'equal))
        (required '()))
    (dolist (slot (schema-slots class))
      (when (and (slot-wire-p slot) (slot-dump-p slot))
        (let ((key (slot-wire-key slot class)))
          (setf (gethash key props)
                (type-json-schema (slot-definition-type slot) slot defs))
          (when (slot-is-required-p slot)
            (push key required)))))
    (dolist (cname (schema-class-computes class))
      (let ((key (style-key cname (schema-class-key-style class)))
            (ht (%js "readOnly" t)))
        (setf (gethash key props) ht)))
    (let ((ht (%js "type" "object")))
      (setf (gethash "properties" ht) props)
      (when required
        (setf (gethash "required" ht) (coerce (nreverse required) 'vector)))
      (let ((extra (schema-class-extra class)))
        (when (and (consp extra) (null (rest extra)))
          (setf extra (first extra)))
        (setf (gethash "additionalProperties" ht) (eq extra :allow)))
      (setf (gethash "title" ht) (string-downcase (symbol-name (class-name class))))
      ht)))

(defun ensure-def (name defs)
  (let ((key (string-downcase (symbol-name name))))
    (unless (gethash key defs)
      (setf (gethash key defs) (make-hash-table :test #'equal))
      (setf (gethash key defs) (object-json-schema (find-schema name) defs)))
    key))

(defun emit-class (schema &key (draft :draft-07))
  (let* ((class (schema-of schema))
         (defs (make-hash-table :test #'equal))
         (root (object-json-schema class defs)))
    (setf (gethash "$schema" root) (draft-uri draft))
    (when (plusp (hash-table-count defs))
      (setf (gethash "$defs" root) defs))
    root))

(defun emit (schema &key (draft :draft-07))
  "SCHEMA-CLASS / name / instance / document → JSON Schema hash-table."
  (cond
    ((json-schema-document-p schema)
     (let ((table (stringify-json (json-schema-table schema))))
       (unless (gethash "$schema" table)
         (setf (gethash "$schema" table) (draft-uri (or draft (json-schema-draft schema)))))
       table))
    ((hash-table-p schema)
     (stringify-json schema))
    (t (emit-class schema :draft draft))))
