(in-package #:schema-protocol-json)

;;; Draft-07 instance validator. CLOS compile-schema stays a separate job.
;;; Local $id / JSON Pointer / URN refs. No remote HTTP fetch.

(defstruct (json-schema-validator (:conc-name validator-))
  root
  draft
  ids
  root-uri)

(defstruct vctx
  validator
  (path nil)
  (issues nil)
  (ref-stack nil)
  (base-uri ""))

(defun json-null-p (value)
  (eq value :null))

(defun json-bool-p (value)
  (or (eq value t) (eq value nil)))

(defun json-object-p (value)
  (hash-table-p value))

(defun json-array-p (value)
  (and (vectorp value) (not (stringp value))))

(defun json-integer-p (value)
  (or (integerp value)
      (and (floatp value) (= value (ftruncate value)))))

(defun json-number-p (value)
  (and (realp value) (not (eq value t)) (not (eq value nil))))

(defun json-type-of (value)
  (cond
    ((json-null-p value) "null")
    ((eq value t) "boolean")
    ((eq value nil) "boolean")
    ((stringp value) "string")
    ((json-integer-p value) "integer")
    ((json-number-p value) "number")
    ((json-object-p value) "object")
    ((json-array-p value) "array")
    (t nil)))

(defun json-equal (a b)
  (cond
    ((eq a b) t)
    ((and (json-null-p a) (json-null-p b)) t)
    ((and (json-number-p a) (json-number-p b)) (= a b))
    ((and (stringp a) (stringp b)) (string= a b))
    ((and (json-object-p a) (json-object-p b))
     (and (= (hash-table-count a) (hash-table-count b))
          (loop for k being the hash-keys of a using (hash-value va)
                always (multiple-value-bind (vb ok) (gethash k b)
                         (and ok (json-equal va vb))))))
    ((and (json-array-p a) (json-array-p b))
     (and (= (length a) (length b))
          (every #'json-equal a b)))
    (t nil)))

(defun vfail (ctx message &optional value)
  (push (make-schema-issue :path (reverse (vctx-path ctx))
                           :message message
                           :value value)
        (vctx-issues ctx))
  nil)

(defun with-path (ctx token fn)
  (push token (vctx-path ctx))
  (unwind-protect (funcall fn)
    (pop (vctx-path ctx))))

;;; URI / $id / $ref --------------------------------------------------------

(defun %split-hash (string)
  (let ((pos (position #\# string)))
    (if pos
        (values (subseq string 0 pos) (subseq string (1+ pos)))
        (values string nil))))

(defun %scheme-end (string)
  (let ((colon (position #\: string)))
    (when (and colon (plusp colon)
               (loop for i from 0 below colon
                     for c = (char string i)
                     always (or (alphanumericp c) (find c "+.-"))))
      colon)))

(defstruct (js-uri (:conc-name js-uri-))
  scheme authority path query fragment opaque-p)

(defun parse-js-uri (string)
  (multiple-value-bind (body frag) (%split-hash (or string ""))
    (let ((scheme nil)
          (authority nil)
          (path body)
          (query nil)
          (opaque nil))
      (let ((colon (%scheme-end body)))
        (when colon
          (setf scheme (subseq body 0 colon)
                body (subseq body (1+ colon)))))
      (cond
        ((and scheme
              (not (and (>= (length body) 2)
                        (char= (char body 0) #\/)
                        (char= (char body 1) #\/))))
         (setf opaque t
               path body))
        (t
         (when (and (>= (length body) 2)
                    (char= (char body 0) #\/)
                    (char= (char body 1) #\/))
           (let* ((rest (subseq body 2))
                  (slash (or (position #\/ rest) (position #\? rest) (length rest))))
             (setf authority (subseq rest 0 slash)
                   body (subseq rest slash))))
         (let ((q (position #\? body)))
           (when q
             (setf query (subseq body (1+ q))
                   body (subseq body 0 q))))
         (setf path body)))
      (make-js-uri :scheme scheme :authority authority :path path
                   :query query :fragment frag :opaque-p opaque))))

(defun render-js-uri (uri &key (fragment t))
  (with-output-to-string (s)
    (when (js-uri-scheme uri)
      (write-string (js-uri-scheme uri) s)
      (write-char #\: s))
    (unless (js-uri-opaque-p uri)
      (when (js-uri-authority uri)
        (write-string "//" s)
        (write-string (js-uri-authority uri) s)))
    (write-string (or (js-uri-path uri) "") s)
    (when (js-uri-query uri)
      (write-char #\? s)
      (write-string (js-uri-query uri) s))
    (when (and fragment (js-uri-fragment uri))
      (write-char #\# s)
      (write-string (js-uri-fragment uri) s))))

(defun %dirname (path)
  (let ((slash (position #\/ path :from-end t)))
    (if slash
        (subseq path 0 (1+ slash))
        "")))

(defun %merge-path (base rel)
  (cond
    ((or (null rel) (string= rel ""))
     (or base ""))
    ((and (plusp (length rel)) (char= (char rel 0) #\/))
     rel)
    (t
     (let ((dir (%dirname (or base "")))
           (acc '()))
       (dolist (part (append (uiop:split-string dir :separator "/")
                             (uiop:split-string rel :separator "/")))
         (cond
           ((or (string= part "") (string= part "."))
            (when (and (string= part "") (null acc))
              (push "" acc)))
           ((string= part "..")
            (when (and acc (not (string= (first acc) "")))
              (pop acc)))
           (t (push part acc))))
       (let ((parts (nreverse acc)))
         (if (and parts (string= (first parts) ""))
             (format nil "~{/~A~}" (rest parts))
             (format nil "~{~A~^/~}" parts)))))))

(defun resolve-js-uri (base ref)
  (let ((b (parse-js-uri (or base "")))
        (r (parse-js-uri ref)))
    (cond
      ((and (null (js-uri-scheme r))
            (null (js-uri-authority r))
            (or (null (js-uri-path r)) (string= (js-uri-path r) ""))
            (null (js-uri-query r)))
       (setf (js-uri-fragment b) (js-uri-fragment r))
       (render-js-uri b))
      ((js-uri-scheme r)
       (render-js-uri r))
      (t
       (setf (js-uri-scheme r) (js-uri-scheme b))
       (cond
         ((js-uri-authority r))
         ((and (js-uri-path r) (plusp (length (js-uri-path r)))
               (char= (char (js-uri-path r) 0) #\/))
          (setf (js-uri-authority r) (js-uri-authority b)))
         (t
          (setf (js-uri-authority r) (js-uri-authority b)
                (js-uri-opaque-p r) (js-uri-opaque-p b))
          (if (js-uri-opaque-p b)
              (setf (js-uri-path r) (or (js-uri-path r) (js-uri-path b)))
              (setf (js-uri-path r) (%merge-path (js-uri-path b) (js-uri-path r))))))
       (render-js-uri r)))))

(defun percent-decode (string)
  (with-output-to-string (out)
    (loop with i = 0
          with n = (length string)
          while (< i n)
          do (let ((c (char string i)))
               (if (and (char= c #\%) (< (+ i 2) n))
                   (let ((code (ignore-errors
                                (parse-integer string :start (1+ i) :end (+ i 3)
                                               :radix 16))))
                     (if code
                         (progn (write-char (code-char code) out) (incf i 3))
                         (progn (write-char c out) (incf i))))
                   (progn (write-char c out) (incf i)))))))

(defun unescape-pointer-token (string)
  (with-output-to-string (out)
    (loop with i = 0
          with n = (length string)
          while (< i n)
          do (let ((c (char string i)))
               (cond
                 ((and (char= c #\~) (< (1+ i) n) (char= (char string (1+ i)) #\1))
                  (write-char #\/ out) (incf i 2))
                 ((and (char= c #\~) (< (1+ i) n) (char= (char string (1+ i)) #\0))
                  (write-char #\~ out) (incf i 2))
                 (t (write-char c out) (incf i)))))))

(defun json-pointer-tokens (pointer)
  (when (and pointer (not (string= pointer "")))
    (unless (char= (char pointer 0) #\/)
      (return-from json-pointer-tokens :anchor))
    (mapcar (lambda (tok)
              (unescape-pointer-token (percent-decode tok)))
            (rest (uiop:split-string pointer :separator "/")))))

(defun pointer-get (node tokens)
  (when (eq tokens :anchor)
    (return-from pointer-get :missing))
  (dolist (tok tokens node)
    (cond
      ((json-object-p node)
       (multiple-value-bind (v ok) (gethash tok node)
         (unless ok
           (return-from pointer-get :missing))
         (setf node v)))
      ((json-array-p node)
       (let ((i (ignore-errors (parse-integer tok :junk-allowed nil))))
         (unless (and i (<= 0 i (1- (length node))))
           (return-from pointer-get :missing))
         (setf node (aref node i))))
      (t (return-from pointer-get :missing)))))

(defun map-subschemas (node fn)
  (unless (json-object-p node)
    (return-from map-subschemas nil))
  (flet ((visit (x)
           (when (or (json-object-p x) (eq x t) (eq x nil))
             (funcall fn x))))
    (dolist (k '("additionalProperties" "additionalItems" "contains"
                 "propertyNames" "if" "then" "else" "not" "items"))
      (multiple-value-bind (v p) (gethash k node)
        (when p
          (if (and (string= k "items") (json-array-p v))
              (map nil #'visit v)
              (visit v)))))
    (dolist (k '("allOf" "anyOf" "oneOf"))
      (let ((v (gethash k node)))
        (when (json-array-p v)
          (map nil #'visit v))))
    (dolist (k '("properties" "patternProperties" "definitions" "$defs"))
      (let ((v (gethash k node)))
        (when (json-object-p v)
          (maphash (lambda (pk pv) (declare (ignore pk)) (visit pv)) v))))
    (let ((deps (gethash "dependencies" node)))
      (when (json-object-p deps)
        (maphash (lambda (k v)
                   (declare (ignore k))
                   (when (or (json-object-p v) (eq v t) (null v))
                     (visit v)))
                 deps)))))

(defun index-ids (node base ids)
  (cond
    ((not (json-object-p node)))
    ((gethash "$ref" node)
     nil)
    (t
     (let ((id (gethash "$id" node))
           (next base))
       (when (stringp id)
         (setf next (resolve-js-uri base id))
         (setf (gethash next ids) node)
         (let ((bare (render-js-uri (parse-js-uri next) :fragment nil)))
           (when (string= bare next)
             (setf (gethash bare ids) node)))
         (let ((frag (js-uri-fragment (parse-js-uri next))))
           (when (and frag (not (and (plusp (length frag)) (char= (char frag 0) #\/))))
             (setf (gethash next ids) node))))
       (map-subschemas node (lambda (child) (index-ids child next ids)))))))

(defun lookup-ref (ctx ref)
  (let* ((resolved (resolve-js-uri (vctx-base-uri ctx) ref))
         (uri (parse-js-uri resolved))
         (frag (js-uri-fragment uri))
         (bare (render-js-uri uri :fragment nil))
         (ids (validator-ids (vctx-validator ctx)))
         (root (validator-root (vctx-validator ctx))))
    (cond
      ((and (or (null (js-uri-scheme uri))
                (string= (or (js-uri-path uri) "") "")
                (string= bare (render-js-uri (parse-js-uri (validator-root-uri
                                                            (vctx-validator ctx)))
                                             :fragment nil)))
            (or (null frag) (string= frag "")
                (and (plusp (length frag)) (char= (char frag 0) #\/))))
       (let ((tokens (json-pointer-tokens (or frag ""))))
         (if (eq tokens :anchor)
             (or (gethash resolved ids)
                 (gethash (concatenate 'string bare "#" frag) ids)
                 :missing)
             (let ((got (pointer-get root (or tokens '()))))
               (if (eq got :missing)
                   (or (gethash resolved ids) :missing)
                   got)))))
      (t
       (or (gethash resolved ids)
           (let ((node (gethash bare ids)))
             (if (and node frag)
                 (let ((tokens (json-pointer-tokens frag)))
                   (cond
                     ((eq tokens :anchor)
                      (or (gethash resolved ids)
                          (gethash (concatenate 'string bare "#" frag) ids)
                          :missing))
                     ((null tokens) node)
                     (t (pointer-get node tokens))))
                 (or node :missing))))))))

;;; Keyword checks ----------------------------------------------------------

(defun type-matches (type value)
  (let ((type (string-downcase (string type))))
    (cond
      ((string= type "integer") (json-integer-p value))
      ((string= type "number") (json-number-p value))
      ((string= type "string") (stringp value))
      ((string= type "boolean") (json-bool-p value))
      ((string= type "null") (json-null-p value))
      ((string= type "object") (json-object-p value))
      ((string= type "array") (json-array-p value))
      (t t))))

(defun multiple-of-p (value factor)
  (when (and (json-number-p value) (json-number-p factor) (not (zerop factor)))
    (let ((q (/ (rationalize value) (rationalize factor))))
      (zerop (mod (numerator q) (denominator q))))))

(defun unique-items-p (seq)
  (loop for i from 0 below (length seq)
        always (loop for j from (1+ i) below (length seq)
                     never (json-equal (elt seq i) (elt seq j)))))

(defun check-pattern (pattern string)
  (handler-case
      (not (null (cl-ppcre:scan pattern string)))
    (error () nil)))

(defun silent-valid-p (ctx schema instance)
  (let ((saved (vctx-issues ctx)))
    (setf (vctx-issues ctx) nil)
    (check-schema ctx schema instance)
    (let ((ok (null (vctx-issues ctx))))
      (setf (vctx-issues ctx) saved)
      ok)))

(defun check-ref (ctx ref instance)
  (let ((node (lookup-ref ctx ref)))
    (when (eq node :missing)
      (vfail ctx (format nil "unresolved $ref ~S" ref))
      (return-from check-ref nil))
    (let ((key (cons node instance)))
      (when (find key (vctx-ref-stack ctx) :test #'equal)
        (return-from check-ref t))
      (push key (vctx-ref-stack ctx))
      (unwind-protect
           (let ((resolved (resolve-js-uri (vctx-base-uri ctx) ref)))
             (let ((next (render-js-uri (parse-js-uri resolved) :fragment nil)))
               (let ((old (vctx-base-uri ctx)))
                 (setf (vctx-base-uri ctx)
                       (if (string= next "") old next))
                 (unwind-protect (check-schema ctx node instance)
                   (setf (vctx-base-uri ctx) old)))))
        (pop (vctx-ref-stack ctx))))))

(defun object-evaluated-keys (schema instance)
  (let ((keys (make-hash-table :test #'equal))
        (props (and (json-object-p schema) (gethash "properties" schema)))
        (pats (and (json-object-p schema) (gethash "patternProperties" schema))))
    (when (json-object-p props)
      (maphash (lambda (k v)
                 (declare (ignore v))
                 (when (nth-value 1 (gethash k instance))
                   (setf (gethash k keys) t)))
               props))
    (when (json-object-p pats)
      (maphash (lambda (pat sub)
                 (declare (ignore sub))
                 (maphash (lambda (k v)
                            (declare (ignore v))
                            (when (check-pattern pat k)
                              (setf (gethash k keys) t)))
                          instance))
               pats))
    keys))

(defun check-object (ctx schema instance)
  (unless (json-object-p instance)
    (return-from check-object t))
  (let ((required (gethash "required" schema))
        (props (gethash "properties" schema))
        (pats (gethash "patternProperties" schema))
        (minp (gethash "minProperties" schema))
        (maxp (gethash "maxProperties" schema))
        (pnames (gethash "propertyNames" schema))
        (deps (gethash "dependencies" schema)))
    (when (and minp (< (hash-table-count instance) minp))
      (vfail ctx (format nil "minProperties ~A" minp) instance))
    (when (and maxp (> (hash-table-count instance) maxp))
      (vfail ctx (format nil "maxProperties ~A" maxp) instance))
    (when required
      (map nil (lambda (k)
                 (let ((key (if (stringp k) k (stringify-key k))))
                   (unless (nth-value 1 (gethash key instance))
                     (with-path ctx key (lambda () (vfail ctx "required"))))))
           required))
    (when (json-object-p props)
      (maphash (lambda (k sub)
                 (multiple-value-bind (v ok) (gethash k instance)
                   (when ok
                     (with-path ctx k (lambda () (check-schema ctx sub v))))))
               props))
    (when (json-object-p pats)
      (maphash (lambda (pat sub)
                 (maphash (lambda (k v)
                            (when (check-pattern pat k)
                              (with-path ctx k (lambda () (check-schema ctx sub v)))))
                          instance))
               pats))
    (multiple-value-bind (ap present) (gethash "additionalProperties" schema)
      (when present
        (let ((seen (object-evaluated-keys schema instance)))
          (maphash (lambda (k v)
                     (unless (gethash k seen)
                       (cond
                         ((eq ap nil)
                          (with-path ctx k (lambda () (vfail ctx "additionalProperties" v))))
                         ((eq ap t) nil)
                         (t (with-path ctx k (lambda () (check-schema ctx ap v)))))))
                   instance))))
    (when pnames
      (maphash (lambda (k v)
                 (declare (ignore v))
                 (with-path ctx k (lambda () (check-schema ctx pnames k))))
               instance))
    (when (json-object-p deps)
      (maphash (lambda (k dep)
                 (when (nth-value 1 (gethash k instance))
                   (cond
                     ((or (json-array-p dep) (listp dep))
                      (map nil (lambda (req)
                                 (let ((rk (if (stringp req) req (stringify-key req))))
                                   (unless (nth-value 1 (gethash rk instance))
                                     (with-path ctx rk
                                       (lambda ()
                                         (vfail ctx (format nil "dependency ~A" k)))))))
                           dep))
                     (t (check-schema ctx dep instance)))))
               deps))))

(defun check-array (ctx schema instance)
  (unless (json-array-p instance)
    (return-from check-array t))
  (let ((items (gethash "items" schema))
        (min (gethash "minItems" schema))
        (max (gethash "maxItems" schema))
        (uniq (gethash "uniqueItems" schema))
        (contains (gethash "contains" schema)))
    (when (and min (< (length instance) min))
      (vfail ctx (format nil "minItems ~A" min) instance))
    (when (and max (> (length instance) max))
      (vfail ctx (format nil "maxItems ~A" max) instance))
    (when (and uniq (not (unique-items-p instance)))
      (vfail ctx "uniqueItems" instance))
    (cond
      ((or (json-object-p items) (eq items t) (eq items nil))
       (when (nth-value 1 (gethash "items" schema))
         (loop for i from 0 below (length instance)
               do (with-path ctx i
                    (lambda () (check-schema ctx items (aref instance i)))))))
      ((json-array-p items)
       (loop for i from 0 below (length instance)
             do (if (< i (length items))
                    (with-path ctx i
                      (lambda () (check-schema ctx (aref items i) (aref instance i))))
                    (multiple-value-bind (ai present) (gethash "additionalItems" schema)
                      (when present
                        (cond
                          ((eq ai nil)
                           (with-path ctx i (lambda () (vfail ctx "additionalItems"))))
                          ((eq ai t) nil)
                          (t (with-path ctx i
                               (lambda () (check-schema ctx ai (aref instance i))))))))))))
    (when (nth-value 1 (gethash "contains" schema))
      (unless (loop for i from 0 below (length instance)
                    thereis (silent-valid-p ctx contains (aref instance i)))
        (vfail ctx "contains" instance)))))

(defun check-string (ctx schema instance)
  (unless (stringp instance)
    (return-from check-string t))
  (let ((min (gethash "minLength" schema))
        (max (gethash "maxLength" schema))
        (pat (gethash "pattern" schema)))
    (when (and min (< (length instance) min))
      (vfail ctx (format nil "minLength ~A" min) instance))
    (when (and max (> (length instance) max))
      (vfail ctx (format nil "maxLength ~A" max) instance))
    (when (and (stringp pat) (not (check-pattern pat instance)))
      (vfail ctx (format nil "pattern ~S" pat) instance))))

(defun check-number (ctx schema instance)
  (unless (json-number-p instance)
    (return-from check-number t))
  (let ((min (gethash "minimum" schema))
        (max (gethash "maximum" schema))
        (emin (gethash "exclusiveMinimum" schema))
        (emax (gethash "exclusiveMaximum" schema))
        (mult (gethash "multipleOf" schema)))
    (when (and (json-number-p min) (< instance min))
      (vfail ctx (format nil "minimum ~A" min) instance))
    (when (and (json-number-p max) (> instance max))
      (vfail ctx (format nil "maximum ~A" max) instance))
    (when (and (json-number-p emin) (<= instance emin))
      (vfail ctx (format nil "exclusiveMinimum ~A" emin) instance))
    (when (and (json-number-p emax) (>= instance emax))
      (vfail ctx (format nil "exclusiveMaximum ~A" emax) instance))
    (when (and (json-number-p mult) (not (multiple-of-p instance mult)))
      (vfail ctx (format nil "multipleOf ~A" mult) instance))))

(defun check-combinators (ctx schema instance)
  (let ((all (gethash "allOf" schema))
        (any (gethash "anyOf" schema))
        (one (gethash "oneOf" schema))
        (neg (gethash "not" schema)))
    (when (json-array-p all)
      (loop for i from 0 below (length all)
            do (check-schema ctx (aref all i) instance)))
    (when (json-array-p any)
      (unless (loop for i from 0 below (length any)
                    thereis (silent-valid-p ctx (aref any i) instance))
        (vfail ctx "anyOf" instance)))
    (when (json-array-p one)
      (let ((n (loop for i from 0 below (length one)
                     count (silent-valid-p ctx (aref one i) instance))))
        (unless (= n 1)
          (vfail ctx (format nil "oneOf matched ~D" n) instance))))
    (when (nth-value 1 (gethash "not" schema))
      (when (silent-valid-p ctx neg instance)
        (vfail ctx "not" instance)))
    (when (nth-value 1 (gethash "if" schema))
      (if (silent-valid-p ctx (gethash "if" schema) instance)
          (when (nth-value 1 (gethash "then" schema))
            (check-schema ctx (gethash "then" schema) instance))
          (when (nth-value 1 (gethash "else" schema))
            (check-schema ctx (gethash "else" schema) instance))))))

(defun check-schema (ctx schema instance)
  (cond
    ((eq schema t) t)
    ((eq schema nil) (vfail ctx "false schema" instance))
    ((not (json-object-p schema))
     (vfail ctx "invalid schema" schema))
    (t
     (let ((ref (gethash "$ref" schema))
           (old-base (vctx-base-uri ctx)))
       (when (and (stringp (gethash "$id" schema)) (null ref))
         (setf (vctx-base-uri ctx)
               (resolve-js-uri old-base (gethash "$id" schema))))
       (unwind-protect
            (cond
              (ref
               (check-ref ctx ref instance))
              (t
               (let ((typ (gethash "type" schema)))
                 (cond
                   ((stringp typ)
                    (unless (type-matches typ instance)
                      (vfail ctx (format nil "type ~A" typ) instance)))
                   ((json-array-p typ)
                    (unless (loop for i from 0 below (length typ)
                                  thereis (type-matches (aref typ i) instance))
                      (vfail ctx (format nil "type ~A" typ) instance)))))
               (multiple-value-bind (const present) (gethash "const" schema)
                 (when present
                   (unless (json-equal instance const)
                     (vfail ctx "const" instance))))
               (let ((enum (gethash "enum" schema)))
                 (when (or (json-array-p enum) (listp enum))
                   (unless (loop for item across (coerce enum 'vector)
                                 thereis (json-equal instance item))
                     (vfail ctx "enum" instance))))
               (check-string ctx schema instance)
               (check-number ctx schema instance)
               (check-object ctx schema instance)
               (check-array ctx schema instance)
               (check-combinators ctx schema instance)))
         (setf (vctx-base-uri ctx) old-base))))))

(defun compile-validator (source &key draft)
  "JSON Schema document → reusable validator (local $ref / $id catalog)."
  (let* ((doc (if (json-schema-validator-p source)
                  (return-from compile-validator source)
                  (if (json-schema-document-p source)
                      source
                      (parse-document source))))
         (root (json-schema-table doc))
         (ids (make-hash-table :test #'equal))
         (root-uri (if (json-object-p root)
                       (let ((id (gethash "$id" root)))
                         (if (stringp id) id ""))
                       "")))
    (setf (gethash "" ids) root)
    (when (plusp (length root-uri))
      (setf (gethash root-uri ids) root)
      (setf (gethash (render-js-uri (parse-js-uri root-uri) :fragment nil) ids) root))
    (index-ids root root-uri ids)
    (make-json-schema-validator :root root
                                :draft (or draft (json-schema-draft doc))
                                :ids ids
                                :root-uri root-uri)))

(defun validate-instance (schema instance)
  "Validate INSTANCE against a JSON Schema document / validator.
   Signals JSON-SCHEMA-VALIDATION-ERROR. Returns INSTANCE on success."
  (let* ((validator (compile-validator schema))
         (data (stringify-json instance))
         (ctx (make-vctx :validator validator
                         :base-uri (or (validator-root-uri validator) ""))))
    (check-schema ctx (validator-root validator) data)
    (when (vctx-issues ctx)
      (error 'json-schema-validation-error
             :issues (nreverse (vctx-issues ctx))))
    instance))

(defun valid-instance-p (schema instance)
  (handler-case
      (progn (validate-instance schema instance) t)
    (json-schema-validation-error () nil)
    (json-schema-ref-error () nil)))
